//
// Generated file, do not edit! Created by opp_msgtool 6.0 from MyMessage.msg.
//

#ifndef __MYMESSAGE_M_H
#define __MYMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class MyMessage;
/**
 * Class generated from <tt>MyMessage.msg:21</tt> by opp_msgtool.
 * <pre>
 * message MyMessage
 * {
 *     int source;
 *     int destination;
 *     int hopecount;
 *     int hosts[];
 *     int nodedata[];
 *     string sndata;
 *     int type;
 * 
 * 
 * 
 * }
 * </pre>
 */
class MyMessage : public ::omnetpp::cMessage
{
  protected:
    int source = 0;
    int destination = 0;
    int hopecount = 0;
    int *hosts = nullptr;
    size_t hosts_arraysize = 0;
    int *nodedata = nullptr;
    size_t nodedata_arraysize = 0;
    omnetpp::opp_string sndata;
    int type = 0;

  private:
    void copy(const MyMessage& other);

  protected:
    bool operator==(const MyMessage&) = delete;

  public:
    MyMessage(const char *name=nullptr, short kind=0);
    MyMessage(const MyMessage& other);
    virtual ~MyMessage();
    MyMessage& operator=(const MyMessage& other);
    virtual MyMessage *dup() const override {return new MyMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSource() const;
    virtual void setSource(int source);

    virtual int getDestination() const;
    virtual void setDestination(int destination);

    virtual int getHopecount() const;
    virtual void setHopecount(int hopecount);

    virtual void setHostsArraySize(size_t size);
    virtual size_t getHostsArraySize() const;
    virtual int getHosts(size_t k) const;
    virtual void setHosts(size_t k, int hosts);
    virtual void insertHosts(size_t k, int hosts);
    [[deprecated]] void insertHosts(int hosts) {appendHosts(hosts);}
    virtual void appendHosts(int hosts);
    virtual void eraseHosts(size_t k);

    virtual void setNodedataArraySize(size_t size);
    virtual size_t getNodedataArraySize() const;
    virtual int getNodedata(size_t k) const;
    virtual void setNodedata(size_t k, int nodedata);
    virtual void insertNodedata(size_t k, int nodedata);
    [[deprecated]] void insertNodedata(int nodedata) {appendNodedata(nodedata);}
    virtual void appendNodedata(int nodedata);
    virtual void eraseNodedata(size_t k);

    virtual const char * getSndata() const;
    virtual void setSndata(const char * sndata);

    virtual int getType() const;
    virtual void setType(int type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MyMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MyMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline MyMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<MyMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MYMESSAGE_M_H

