//
// Generated file, do not edit! Created by opp_msgtool 6.0 from CustomMsg.msg.
//

#ifndef __CUSTOMMSG_M_H
#define __CUSTOMMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class CustomMsg;
/**
 * Class generated from <tt>CustomMsg.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message CustomMsg
 * {
 *     int source;
 *     int destination;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class CustomMsg : public ::omnetpp::cMessage
{
  protected:
    int source = 0;
    int destination = 0;
    int hopCount = 0;

  private:
    void copy(const CustomMsg& other);

  protected:
    bool operator==(const CustomMsg&) = delete;

  public:
    CustomMsg(const char *name=nullptr, short kind=0);
    CustomMsg(const CustomMsg& other);
    virtual ~CustomMsg();
    CustomMsg& operator=(const CustomMsg& other);
    virtual CustomMsg *dup() const override {return new CustomMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSource() const;
    virtual void setSource(int source);

    virtual int getDestination() const;
    virtual void setDestination(int destination);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CustomMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CustomMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline CustomMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<CustomMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CUSTOMMSG_M_H

